version: "3.7"

services:

  app:
    image: nginx
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/app/:/etc/nginx/app/
    ports:
      - "80:80"
    networks:
      - nginx_net

networks:
  nginx_net: null
    # driver: bridge
    # driver_opts:
    # encrypted: "true"
